deploy: 631077328123de89bfe95941faa6e1796d9d597c

diff --git a/target/docker/datasets/loaders/openproblems_neurips2021_bmmc/openproblems_neurips2021_bmmc b/target/docker/datasets/loaders/openproblems_neurips2021_bmmc/openproblems_neurips2021_bmmc
--- a/target/docker/datasets/loaders/openproblems_neurips2021_bmmc/openproblems_neurips2021_bmmc
+++ b/target/docker/datasets/loaders/openproblems_neurips2021_bmmc/openproblems_neurips2021_bmmc
@@ -192,6 +192,10 @@ function ViashHelp {
   echo "        Name of the second modality."
   echo ""
   echo "Metadata:"
+  echo "    --dataset_id"
+  echo "        type: string, required parameter"
+  echo "        A unique identifier for the dataset"
+  echo ""
   echo "    --dataset_name"
   echo "        type: string, required parameter"
   echo "        Nicely formatted name."
@@ -448,9 +452,9 @@ ENTRYPOINT []
  
 RUN :
 LABEL org.opencontainers.image.description="Companion container for running component datasets/loaders openproblems_neurips2021_bmmc"
-LABEL org.opencontainers.image.created="2024-02-06T12:34:11Z"
+LABEL org.opencontainers.image.created="2024-02-26T08:18:44Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/openproblems-v2"
-LABEL org.opencontainers.image.revision="e3c59971146b6d022bdf73d3c3ebe366c6a4144b"
+LABEL org.opencontainers.image.revision="631077328123de89bfe95941faa6e1796d9d597c"
 LABEL org.opencontainers.image.version="integration_build"
 
 VIASHDOCKER
@@ -636,6 +640,17 @@ while [[ $# -gt 0 ]]; do
         --mod2=*)
             [ -n "$VIASH_PAR_MOD2" ] && ViashError Bad arguments for option \'--mod2=*\': \'$VIASH_PAR_MOD2\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_MOD2=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --dataset_id)
+            [ -n "$VIASH_PAR_DATASET_ID" ] && ViashError Bad arguments for option \'--dataset_id\': \'$VIASH_PAR_DATASET_ID\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_DATASET_ID="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --dataset_id. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --dataset_id=*)
+            [ -n "$VIASH_PAR_DATASET_ID" ] && ViashError Bad arguments for option \'--dataset_id=*\': \'$VIASH_PAR_DATASET_ID\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_DATASET_ID=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         --dataset_name)
@@ -856,6 +871,10 @@ if [ -z ${VIASH_PAR_MOD2+x} ]; then
   ViashError '--mod2' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
+if [ -z ${VIASH_PAR_DATASET_ID+x} ]; then
+  ViashError '--dataset_id' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_PAR_DATASET_NAME+x} ]; then
   ViashError '--dataset_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -1030,6 +1049,7 @@ par = {
   'input': $( if [ ! -z ${VIASH_PAR_INPUT+x} ]; then echo "r'${VIASH_PAR_INPUT//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'mod1': $( if [ ! -z ${VIASH_PAR_MOD1+x} ]; then echo "r'${VIASH_PAR_MOD1//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'mod2': $( if [ ! -z ${VIASH_PAR_MOD2+x} ]; then echo "r'${VIASH_PAR_MOD2//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'dataset_id': $( if [ ! -z ${VIASH_PAR_DATASET_ID+x} ]; then echo "r'${VIASH_PAR_DATASET_ID//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'dataset_name': $( if [ ! -z ${VIASH_PAR_DATASET_NAME+x} ]; then echo "r'${VIASH_PAR_DATASET_NAME//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'dataset_url': $( if [ ! -z ${VIASH_PAR_DATASET_URL+x} ]; then echo "r'${VIASH_PAR_DATASET_URL//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'dataset_reference': $( if [ ! -z ${VIASH_PAR_DATASET_REFERENCE+x} ]; then echo "r'${VIASH_PAR_DATASET_REFERENCE//\'/\'\"\'\"r\'}'"; else echo None; fi ),
