deploy: 5d9f4c83fca0b1e371eb198306a59a33c16340d8

diff --git a/target/docker/batch_integration/metrics/asw_batch/asw_batch b/target/docker/batch_integration/metrics/asw_batch/asw_batch
--- a/target/docker/batch_integration/metrics/asw_batch/asw_batch
+++ b/target/docker/batch_integration/metrics/asw_batch/asw_batch
@@ -159,14 +159,12 @@ function ViashHelp {
   echo ""
   echo "Arguments:"
   echo "    --input_integrated"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        example: resources_test/batch_integration/pancreas/scvi.h5ad"
-  echo "        Integrated AnnData HDF5 file."
   echo ""
   echo "    --output"
-  echo "        type: file, output, file must exist"
+  echo "        type: file, required parameter, output, file must exist"
   echo "        example: score.h5ad"
-  echo "        Metric score file"
 }
 
 ######## Helper functions for setting up Docker images for viash ########
@@ -384,15 +382,15 @@ function ViashDockerCheckCommands {
 #   ViashDockerFile
 function ViashDockerfile {
   cat << 'VIASHDOCKER'
-FROM ghcr.io/openproblems-bio/base-r:latest
+FROM ghcr.io/openproblems-bio/base_r:1.0.0
 
 RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "scanpy" "scib==1.1.3"
 
 LABEL org.opencontainers.image.description="Companion container for running component batch_integration/metrics asw_batch"
-LABEL org.opencontainers.image.created="2023-06-13T07:13:25Z"
+LABEL org.opencontainers.image.created="2023-06-14T00:54:02Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/openproblems-v2"
-LABEL org.opencontainers.image.revision="18bdfdfd0184487e64b805653765452dded04a6c"
+LABEL org.opencontainers.image.revision="5d9f4c83fca0b1e371eb198306a59a33c16340d8"
 LABEL org.opencontainers.image.version="main_build"
 VIASHDOCKER
 }
@@ -685,6 +683,14 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_INPUT_INTEGRATED+x} ]; then
+  ViashError '--input_integrated' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_OUTPUT+x} ]; then
+  ViashError '--output' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
diff --git a/target/docker/denoising/methods/magic/magic b/target/docker/denoising/methods/magic/magic
--- a/target/docker/denoising/methods/magic/magic
+++ b/target/docker/denoising/methods/magic/magic
@@ -159,12 +159,12 @@ function ViashHelp {
   echo ""
   echo "Arguments:"
   echo "    --input_train"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        example: resources_test/denoising/pancreas/train.h5ad"
   echo "        The training data"
   echo ""
   echo "    --output"
-  echo "        type: file, output, file must exist"
+  echo "        type: file, required parameter, output, file must exist"
   echo "        example: resources_test/denoising/pancreas/magic.h5ad"
   echo "        The denoised data"
   echo ""
@@ -406,15 +406,15 @@ function ViashDockerCheckCommands {
 #   ViashDockerFile
 function ViashDockerfile {
   cat << 'VIASHDOCKER'
-FROM ghcr.io/openproblems-bio/base-python:latest
+FROM ghcr.io/openproblems-bio/base_python:1.0.0
 
 RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "scprep" "magic-impute" "scipy" "scikit-learn<1.2"
 
 LABEL org.opencontainers.image.description="Companion container for running component denoising/methods magic"
-LABEL org.opencontainers.image.created="2023-06-13T07:13:29Z"
+LABEL org.opencontainers.image.created="2023-06-14T00:54:06Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/openproblems-v2"
-LABEL org.opencontainers.image.revision="18bdfdfd0184487e64b805653765452dded04a6c"
+LABEL org.opencontainers.image.revision="5d9f4c83fca0b1e371eb198306a59a33c16340d8"
 LABEL org.opencontainers.image.version="main_build"
 VIASHDOCKER
 }
@@ -751,6 +751,14 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_INPUT_TRAIN+x} ]; then
+  ViashError '--input_train' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_OUTPUT+x} ]; then
+  ViashError '--output' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
diff --git a/target/docker/label_projection/methods/xgboost/xgboost b/target/docker/label_projection/methods/xgboost/xgboost
--- a/target/docker/label_projection/methods/xgboost/xgboost
+++ b/target/docker/label_projection/methods/xgboost/xgboost
@@ -157,23 +157,18 @@ VIASH_META_TEMP_DIR="$VIASH_TEMP"
 function ViashHelp {
   echo "xgboost main_build"
   echo ""
-  echo "XGBoost: A Scalable Tree Boosting System"
-  echo ""
   echo "Arguments:"
   echo "    --input_train"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        example: resources_test/label_projection/pancreas/train.h5ad"
-  echo "        The training data"
   echo ""
   echo "    --input_test"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        example: resources_test/label_projection/pancreas/test.h5ad"
-  echo "        The test data (without labels)"
   echo ""
   echo "    --output"
-  echo "        type: file, output, file must exist"
+  echo "        type: file, required parameter, output, file must exist"
   echo "        example: resources_test/label_projection/pancreas/knn.h5ad"
-  echo "        The prediction file"
 }
 
 ######## Helper functions for setting up Docker images for viash ########
@@ -391,15 +386,15 @@ function ViashDockerCheckCommands {
 #   ViashDockerFile
 function ViashDockerfile {
   cat << 'VIASHDOCKER'
-FROM ghcr.io/openproblems-bio/base-python:latest
+FROM ghcr.io/openproblems-bio/base_python:1.0.0
 
 RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "xgboost"
 
 LABEL org.opencontainers.image.description="Companion container for running component label_projection/methods xgboost"
-LABEL org.opencontainers.image.created="2023-06-13T07:13:28Z"
+LABEL org.opencontainers.image.created="2023-06-14T00:54:05Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/openproblems-v2"
-LABEL org.opencontainers.image.revision="18bdfdfd0184487e64b805653765452dded04a6c"
+LABEL org.opencontainers.image.revision="5d9f4c83fca0b1e371eb198306a59a33c16340d8"
 LABEL org.opencontainers.image.version="main_build"
 VIASHDOCKER
 }
@@ -703,6 +698,18 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_INPUT_TRAIN+x} ]; then
+  ViashError '--input_train' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_INPUT_TEST+x} ]; then
+  ViashError '--input_test' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_OUTPUT+x} ]; then
+  ViashError '--output' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
diff --git a/target/docker/label_projection/process_dataset/process_dataset b/target/docker/label_projection/process_dataset/process_dataset
--- a/target/docker/label_projection/process_dataset/process_dataset
+++ b/target/docker/label_projection/process_dataset/process_dataset
@@ -159,26 +159,20 @@ function ViashHelp {
   echo ""
   echo "Arguments:"
   echo "    --input"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        example: resources_test/common/pancreas/dataset.h5ad"
-  echo "        A dataset processed by the common dataset processing pipeline."
-  echo "        This dataset contains both raw counts and normalized data matrices,"
-  echo "        as well as a PCA embedding, HVG selection and a kNN graph."
   echo ""
   echo "    --output_train"
-  echo "        type: file, output, file must exist"
+  echo "        type: file, required parameter, output, file must exist"
   echo "        example: resources_test/label_projection/pancreas/train.h5ad"
-  echo "        The training data"
   echo ""
   echo "    --output_test"
-  echo "        type: file, output, file must exist"
+  echo "        type: file, required parameter, output, file must exist"
   echo "        example: resources_test/label_projection/pancreas/test.h5ad"
-  echo "        The test data (without labels)"
   echo ""
   echo "    --output_solution"
-  echo "        type: file, output, file must exist"
+  echo "        type: file, required parameter, output, file must exist"
   echo "        example: resources_test/label_projection/pancreas/solution.h5ad"
-  echo "        The solution for the test data"
   echo ""
   echo "    --method"
   echo "        type: string"
@@ -417,13 +411,13 @@ function ViashDockerCheckCommands {
 #   ViashDockerFile
 function ViashDockerfile {
   cat << 'VIASHDOCKER'
-FROM ghcr.io/openproblems-bio/base-python:latest
+FROM ghcr.io/openproblems-bio/base_python:1.0.0
 
 RUN :
 LABEL org.opencontainers.image.description="Companion container for running component label_projection process_dataset"
-LABEL org.opencontainers.image.created="2023-06-13T07:13:30Z"
+LABEL org.opencontainers.image.created="2023-06-14T00:54:07Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/openproblems-v2"
-LABEL org.opencontainers.image.revision="18bdfdfd0184487e64b805653765452dded04a6c"
+LABEL org.opencontainers.image.revision="5d9f4c83fca0b1e371eb198306a59a33c16340d8"
 LABEL org.opencontainers.image.version="main_build"
 VIASHDOCKER
 }
@@ -782,6 +776,22 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_INPUT+x} ]; then
+  ViashError '--input' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_OUTPUT_TRAIN+x} ]; then
+  ViashError '--output_train' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_OUTPUT_TEST+x} ]; then
+  ViashError '--output_test' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_OUTPUT_SOLUTION+x} ]; then
+  ViashError '--output_solution' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
